#!/usr/bin/env python3
"""Bulk-upload HEHEARSE emoji to Telegram via Bot API.

Reads the manifest.json generated by generate_emojis.py and uploads
all emoji as a custom emoji sticker set. Supports resuming interrupted uploads.
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import requests

API_BASE = "https://api.telegram.org/bot{token}"
TOOLS_DIR = Path(__file__).resolve().parent
DEFAULT_EMOJI_DIR = TOOLS_DIR / "emojis"
DEFAULT_SET_TITLE = "HEHEARSE"


def api_call(token, method, data=None, files=None, retries=3):
    """Call a Telegram Bot API method with retry logic."""
    url = f"{API_BASE.format(token=token)}/{method}"
    for attempt in range(retries):
        try:
            resp = requests.post(url, data=data, files=files, timeout=30)
            result = resp.json()
            if result.get("ok"):
                return result.get("result")

            error_code = result.get("error_code", 0)
            description = result.get("description", "Unknown error")

            if error_code == 429:
                retry_after = result.get("parameters", {}).get("retry_after", 5)
                print(f"  Rate limited, waiting {retry_after}s...")
                time.sleep(retry_after)
                continue

            return {"error": True, "error_code": error_code,
                    "description": description}

        except requests.exceptions.RequestException as e:
            if attempt < retries - 1:
                wait = 2 ** (attempt + 1)
                print(f"  Network error ({e}), retrying in {wait}s...")
                time.sleep(wait)
            else:
                return {"error": True, "description": str(e)}

    return {"error": True, "description": "Max retries exceeded"}


def get_bot_username(token):
    result = api_call(token, "getMe")
    if isinstance(result, dict) and result.get("error"):
        print(f"ERROR: Could not reach bot API: {result['description']}")
        sys.exit(1)
    return result["username"]


def get_sticker_set(token, name):
    result = api_call(token, "getStickerSet", {"name": name})
    if isinstance(result, dict) and result.get("error"):
        return None
    return result


def create_sticker_set(token, user_id, name, title, sticker_path, emoji_list):
    """Create a new custom emoji sticker set with the first sticker."""
    with open(str(sticker_path), "rb") as f:
        sticker_obj = {
            "sticker": "attach://sticker_file",
            "format": "static",
            "emoji_list": emoji_list,
        }
        data = {
            "user_id": user_id,
            "name": name,
            "title": title,
            "sticker_type": "custom_emoji",
            "stickers": json.dumps([sticker_obj]),
        }
        files = {"sticker_file": ("sticker.png", f, "image/png")}
        return api_call(token, "createNewStickerSet", data=data, files=files)


def add_sticker_to_set(token, user_id, name, sticker_path, emoji_list):
    """Add a sticker to an existing set."""
    with open(str(sticker_path), "rb") as f:
        sticker_obj = {
            "sticker": "attach://sticker_file",
            "format": "static",
            "emoji_list": emoji_list,
        }
        data = {
            "user_id": user_id,
            "name": name,
            "sticker": json.dumps(sticker_obj),
        }
        files = {"sticker_file": ("sticker.png", f, "image/png")}
        return api_call(token, "addStickerToSet", data=data, files=files)


def main():
    parser = argparse.ArgumentParser(description="Upload HEHEARSE emoji to Telegram")
    parser.add_argument("--token", help="Bot token (or set TELEGRAM_BOT_TOKEN)")
    parser.add_argument("--user-id", help="Your Telegram user ID (or set TELEGRAM_USER_ID)")
    parser.add_argument("--emoji-dir", default=str(DEFAULT_EMOJI_DIR))
    parser.add_argument("--set-name", help="Override sticker set name")
    parser.add_argument("--set-title", default=DEFAULT_SET_TITLE)
    parser.add_argument("--dry-run", action="store_true",
                        help="Validate everything without uploading")
    parser.add_argument("--force", action="store_true",
                        help="Delete and recreate the set if it exists")
    args = parser.parse_args()

    token = args.token or os.environ.get("TELEGRAM_BOT_TOKEN")
    user_id = args.user_id or os.environ.get("TELEGRAM_USER_ID")

    if not token:
        print("ERROR: Bot token required. Set TELEGRAM_BOT_TOKEN or use --token")
        sys.exit(1)
    if not user_id:
        print("ERROR: User ID required. Set TELEGRAM_USER_ID or use --user-id")
        sys.exit(1)

    emoji_dir = Path(args.emoji_dir)
    manifest_path = emoji_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"ERROR: No manifest.json in {emoji_dir}")
        print("Run generate_emojis.py first.")
        sys.exit(1)

    with open(str(manifest_path)) as f:
        manifest = json.load(f)

    # Validate all files exist
    missing = []
    for entry in manifest:
        fp = emoji_dir / entry["filename"]
        if not fp.exists():
            missing.append(entry["filename"])
    if missing:
        print(f"ERROR: {len(missing)} files missing: {missing[:5]}...")
        sys.exit(1)

    # Get bot info
    print("Connecting to Telegram Bot API...")
    bot_username = get_bot_username(token)
    print(f"  Bot: @{bot_username}")

    set_name = args.set_name or f"hehearse_emoji_by_{bot_username}"
    print(f"  Set name: {set_name}")
    print(f"  Set title: {args.set_title}")
    print(f"  Emoji count: {len(manifest)}")

    if args.dry_run:
        print("\n[DRY RUN] Validation passed. Ready to upload.")
        existing = get_sticker_set(token, set_name)
        if existing:
            print(f"  Set already exists with {len(existing.get('stickers', []))} stickers")
        else:
            print("  Set does not exist yet (will be created)")
        return

    # Check existing set
    existing = get_sticker_set(token, set_name)
    start_index = 0

    if existing and args.force:
        print("\n  --force: Removing all stickers from existing set...")
        for sticker in existing.get("stickers", []):
            api_call(token, "deleteStickerFromSet",
                     {"sticker": sticker["file_id"]})
            time.sleep(0.05)
        existing = None

    if existing:
        existing_count = len(existing.get("stickers", []))
        print(f"\n  Set exists with {existing_count}/{len(manifest)} stickers")
        if existing_count >= len(manifest):
            print("  All emoji already uploaded!")
            print(f"\n  Set URL: https://t.me/addstickers/{set_name}")
            return
        start_index = existing_count
        print(f"  Resuming from sticker #{start_index + 1}...")

    # Upload
    print(f"\nUploading {len(manifest) - start_index} emoji...")
    errors = []

    for i, entry in enumerate(manifest):
        if i < start_index:
            continue

        fp = emoji_dir / entry["filename"]
        emoji_list = entry.get("emoji_list", ["⭐"])
        label = f"[{i + 1}/{len(manifest)}]"

        if i == 0 and not existing:
            print(f"  {label} Creating set with {entry['filename']}...")
            result = create_sticker_set(
                token, user_id, set_name, args.set_title, fp, emoji_list
            )
        else:
            result = add_sticker_to_set(
                token, user_id, set_name, fp, emoji_list
            )

        if isinstance(result, dict) and result.get("error"):
            errors.append((entry["filename"], result["description"]))
            print(f"  {label} FAILED {entry['filename']}: {result['description']}")
        else:
            print(f"  {label} {entry['filename']}")

        time.sleep(0.05)

    # Summary
    print(f"\nDone! {len(manifest) - start_index - len(errors)} uploaded, {len(errors)} errors.")
    if errors:
        print("\nFailed uploads:")
        for fn, desc in errors:
            print(f"  {fn}: {desc}")

    print(f"\nSet URL: https://t.me/addstickers/{set_name}")


if __name__ == "__main__":
    main()
